customhost = "employee.c5vgzpoixgod.ap-south-1.rds.amazonaws.com"
customuser = "harshit"
custompass = "khandelwal1969"
customdb = "employee"
custombucket = "addemployee1234"
customregion = "ap-south-1"
